### ISSUE TITLE
external link icon only for links spelled out in html

### ISSUE THREAD

**Issue by dalejbarr** [PsyTeachR/book-template#3]
Right now if you put in an external link using
`<a href="google.com">the link</a>` you get a nice little icon showing that the link will open in an new tab.

However, would be nice if you could also get the icon if you specify the link using markdown:
`[the link](google.com){target="_blank"}`

**Comment by debruine** [comment]
The css controls this, and is set to display the external icon for any link with `target="_blank"`, so this does work. I added some instruction at https://psyteachr.github.io/book-template/psyteachr-style-guide.html#links

```
a[target="_blank"]::after {
  content: url("../images/icons/link_external.svg");
  margin: 0 3px 0 5px;
}
```
